# Site settings
title: Anurag Malyala
email: anuragmalyala9001@gmail.com
url: https://IsCoelacanth.github.io
description: "Looks like you found my site! Computer Science Senior at Delhi Technological University. Research and Development enthusiast, specializing in Artificial Intelligence and Machine learning."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Anurag Malyala

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Derpguy9001
  - title: facebook
    url: http://facebook.com/AnuragMalyala9001
  - title: github
    url: https://github.com/IsCoelacanth
  - title: instagram
    url: https://instagram.com/Derpguy9001
  - title: linkedin
    url: https://linkedin.com/in/AnuragMalyala9001

# Build settings
markdown: kramdown
permalink: pretty
